pip install/懒加载/用户Meta
AmiyaBot/Amiya-Bot pull request #135
Opened 2022-10-22 15:04 UTC by hsyhhssyy

这个PR里有三个改动：
1、加入对插件路径执行 pip install -r requirements.txt 的操作
在加载所有插件前，他会遍历每个文件夹寻找requirements.txt，如果有，就会调用pip进行安装

2、加入一个LazyLoadPluginInstance，为插件提供对抗依赖的手段
未来，如果插件之间互相产生依赖，为了防止A插件加载时，他依赖的B插件还没加载，加入一个load虚函数，涉及到插件依赖的代码可以移动到虚函数load中，当load被调用时，bot承诺所有插件的install都已经执行。

3、增加一个新的用户字段meta_json
除了新字段，还增加了两个新函数用于get meta和set meta，这样插件可以通过这个，在用户级别上，保存持久化数据。
但是因为python没有private能力，其他插件可以轻易毁掉另一个插件辛苦积累的数据，不过这是py，没办法

2022-10-22 15:06 UTC, Initial-heart-1 commented
建议对 PR 进行拆分。部分改动我认为可以很快的合并，而另一部分则不一定。如果放在一个 PR 里，可能对合并产生影响。另外，你需要在 PR 中提到涉及到的 issue，例如 #132 。

2022-10-25 02:13 UTC, vivien8261 requested changes
这里有两个问题：
1. 插件并不是绑定本仓库进行开发的，`LazyLoadPluginInstance` 类在开发过程中如何导入？我觉得它应该写在 core 项目下。
2. 如果项目打包成了可执行文件，那么用户本地未必有 python 环境，就算有，pip 安装的库也不会被可执行文件加载。即使是修改 sys.path 达到目的，过程也非常不友好了。自动安装依赖的想法非常好，但是方法有待商榷。

2022-10-25 02:27 UTC, Well2333 commented
> 这里有两个问题：
> 1. 插件并不是绑定本仓库进行开发的，`LazyLoadPluginInstance` 类在开发过程中如何导入？我觉得它应该写在 core 项目下。
> 2. 如果项目打包成了可执行文件，那么用户本地未必有 python 环境，就算有，pip 安装的库也不会被可执行文件加载。即使是修改 sys.path 达到目的，过程也非常不友好了。自动安装依赖的想法非常好，但是方法有待商榷。

个人认为，如果打包成了可执行文件的形式，那么便不应该继续为其直接添加插件，因为这并不仅是第三方库的问题，也有可能出现标准库的问题，若需要添加插件的话应在合适的Python环境中添加并再次打包。
综上所述，第二条问题个人认为是无法解决且无意义的，不应为此牺牲掉源码部署的便利性。

2022-10-25 02:39 UTC, vivien8261 commented
> > 这里有两个问题：
> > 
> > 1. 插件并不是绑定本仓库进行开发的，`LazyLoadPluginInstance` 类在开发过程中如何导入？我觉得它应该写在 core 项目下。
> > 2. 如果项目打包成了可执行文件，那么用户本地未必有 python 环境，就算有，pip 安装的库也不会被可执行文件加载。即使是修改 sys.path 达到目的，过程也非常不友好了。自动安装依赖的想法非常好，但是方法有待商榷。
> 
> 个人认为，如果打包成了可执行文件的形式，那么便不应该继续为其直接添加插件，因为这并不仅是第三方库的问题，也有可能出现标准库的问题，若需要添加插件的话应在合适的Python环境中添加并再次打包。 综上所述，第二条问题个人认为是无法解决且无意义的，不应为此牺牲掉源码部署的便利性。

打包的的可执行文件以资源文件的方式加载了3.8的全部标准库。

2022-10-25 02:43 UTC, Well2333 commented
> > > 这里有两个问题：
> > > 
> > > 1. 插件并不是绑定本仓库进行开发的，`LazyLoadPluginInstance` 类在开发过程中如何导入？我觉得它应该写在 core 项目下。
> > > 2. 如果项目打包成了可执行文件，那么用户本地未必有 python 环境，就算有，pip 安装的库也不会被可执行文件加载。即使是修改 sys.path 达到目的，过程也非常不友好了。自动安装依赖的想法非常好，但是方法有待商榷。
> > 
> > 
> > 个人认为，如果打包成了可执行文件的形式，那么便不应该继续为其直接添加插件，因为这并不仅是第三方库的问题，也有可能出现标准库的问题，若需要添加插件的话应在合适的Python环境中添加并再次打包。 综上所述，第二条问题个人认为是无法解决且无意义的，不应为此牺牲掉源码部署的便利性。
> 
> 打包的的可执行文件以资源文件的方式加载了3.8的全部标准库。


是的，但这本身就存在风险，例如用户使用了3.9+的新增方法，默认加载3.8并不能解决此类问题（虽然发生概率不高）。
二进制版本本身并不应该具有此类拓展性，应在源码的基础上进行拓展并重新打包。

2022-10-25 02:46 UTC, Well2333 requested changes

2022-10-25 02:46 UTC, Well2333 commented on core/__init__.py
> +                    subprocess.run([sys.executable, "-m", "pip", "install", "-r", req_file, "-i","https://pypi.tuna.tsinghua.edu.cn/simple"])
这种安装方法对于虚拟环境的支持可能存在问题。同时也有注入漏洞的风险。
虚拟环境支持目前个人没有好的解决办法，但第二条可以通过导入pip库的方法进行安全的安装。例如：
```py
from pip._internal import main
main.main(['install', '第三方库名'])
```

2022-10-25 02:46 UTC, vivien8261 commented
> > > > 这里有两个问题：
> > > > 
> > > > 1. 插件并不是绑定本仓库进行开发的，`LazyLoadPluginInstance` 类在开发过程中如何导入？我觉得它应该写在 core 项目下。
> > > > 2. 如果项目打包成了可执行文件，那么用户本地未必有 python 环境，就算有，pip 安装的库也不会被可执行文件加载。即使是修改 sys.path 达到目的，过程也非常不友好了。自动安装依赖的想法非常好，但是方法有待商榷。
> > > 
> > > 
> > > 个人认为，如果打包成了可执行文件的形式，那么便不应该继续为其直接添加插件，因为这并不仅是第三方库的问题，也有可能出现标准库的问题，若需要添加插件的话应在合适的Python环境中添加并再次打包。 综上所述，第二条问题个人认为是无法解决且无意义的，不应为此牺牲掉源码部署的便利性。
> > 
> > 
> > 打包的的可执行文件以资源文件的方式加载了3.8的全部标准库。
> 
> 是的，但这本身就存在风险，例如用户使用了3.9+的新增方法，默认加载3.8并不能解决此类问题（虽然发生概率不高）。 二进制版本本身并不应该具有此类拓展性，应在源码的基础上进行拓展并重新打包。

那插件依然可以自带 3.9 的标准库文件，只需要有合适的方式提供 exe 不存在的依赖就行了，即使要用 pip 安装到当前环境，也得考虑插件之间的依赖版本是否冲突。这个问题实现起来需要考虑的事情非常多。

2022-10-25 02:50 UTC, Well2333 commented
> > > > > 这里有两个问题：
> > > > > 
> > > > > 1. 插件并不是绑定本仓库进行开发的，`LazyLoadPluginInstance` 类在开发过程中如何导入？我觉得它应该写在 core 项目下。
> > > > > 2. 如果项目打包成了可执行文件，那么用户本地未必有 python 环境，就算有，pip 安装的库也不会被可执行文件加载。即使是修改 sys.path 达到目的，过程也非常不友好了。自动安装依赖的想法非常好，但是方法有待商榷。
> > > > 
> > > > 
> > > > 个人认为，如果打包成了可执行文件的形式，那么便不应该继续为其直接添加插件，因为这并不仅是第三方库的问题，也有可能出现标准库的问题，若需要添加插件的话应在合适的Python环境中添加并再次打包。 综上所述，第二条问题个人认为是无法解决且无意义的，不应为此牺牲掉源码部署的便利性。
> > > 
> > > 
> > > 打包的的可执行文件以资源文件的方式加载了3.8的全部标准库。
> > 
> > 
> > 是的，但这本身就存在风险，例如用户使用了3.9+的新增方法，默认加载3.8并不能解决此类问题（虽然发生概率不高）。 二进制版本本身并不应该具有此类拓展性，应在源码的基础上进行拓展并重新打包。
> 
> 那插件依然可以自带 3.9 的标准库文件，只需要有合适的方式提供 exe 不存在的依赖就行了，即使要用 pip 安装到当前环境，也得考虑插件之间的依赖版本是否冲突。这个问题实现起来需要考虑的事情非常多。

是的，而且这还并不是最难的问题，正如我前文所述，对于虚拟环境来说这种安装方式是否生效还不得而知，但对于非conda类型的虚拟环境来说，其lock文件必然会受到影响

2022-10-25 02:54 UTC, Well2333 commented
实际上这涉及到一个问题，amiyabot的插件系统是想做成傻瓜式的“拖进来就能用”甚至打包版都能使用的强兼容方案？还是类似nonebot这种需要自己管理依赖，相对自由但对于新手并不怎么友好的方案？

2022-10-25 02:58 UTC, vivien8261 commented
> 实际上这涉及到一个问题，amiyabot的插件系统是想做成傻瓜式的“拖进来就能用”甚至打包版都能使用的强兼容方案？还是类似nonebot这种需要自己管理依赖，相对自由但对于新手并不怎么友好的方案？

就是前者，python 的 zipimport 和 importlib 配合 sys.path 机制，可以达到在可执行文件不存在这个依赖的情况下依然能加载这个模块的效果，这是目前插件的实现思路。任何需要后期加载的依赖，都可以通过 sys.path 加进当前环境里，也能在加载完成后移除这个依赖。

2022-10-25 03:04 UTC, Well2333 commented
> > 实际上这涉及到一个问题，amiyabot的插件系统是想做成傻瓜式的“拖进来就能用”甚至打包版都能使用的强兼容方案？还是类似nonebot这种需要自己管理依赖，相对自由但对于新手并不怎么友好的方案？
> 
> 就是前者，python 的 zipimport 和 importlib 配合 sys.path 机制，可以达到在可执行文件不存在这个依赖的情况下依然能加载这个模块的效果，这是目前插件的实现思路。任何需要后期加载的依赖，都可以通过 sys.path 加进当前环境里，也能在加载完成后移除这个依赖。

对于前者而言，应该是让插件作者把依赖扔到自己的插件目录下，自己管自己。这样虽然空间利用率很低，但是最安全，也很傻瓜式，兼容性也是最好的（不涉及venv等问题）。因此个人认为此pr的依赖管理功能并不需要合并，维持现状（指当前的管理方法）即可。

2022-10-25 03:30 UTC, hsyhhssyy commented
你们上面讨论了pip的问题
这里我回答一下LazyLoad的问题
LazyLoad为什么放在这里而不是Core，是因为，不管是原来的PluginInstance，还是LazyLoadPluginInstance，他们加载的代码都在这里，也就是说使用者在这里。
如果你把他移动到core，那么“确保load函数在所有插件加载完成后才被执行”这个条件就无法保证了。
如果一个开发者单独使用core，那么这个LazyLoadPluginInstance对他毫无用处，因为插件的加载顺序是由他代码控制的。

2022-10-25 03:39 UTC, hsyhhssyy commented
关于插件系统，我稍微多一嘴。
我觉得，以python的语言能力，以你现在的模式来提供插件功能，就必然意味着放弃了exe部署的能力，这两者是冲突的，以exe方式（pyinstaller ）发布的产品，天然就无法再加载任何插件，因为目前你的插件设计机制不是http进程隔离，而是直接代码引入。
（我其实前几天在群里讨论进程间通信的时候好像提过一嘴，说我认为目前进程间通信的最优解就是http，当然也可能是别的群）
而代码引入，就必然会导致环境污染和库污染，这是无法解决的问题。
与其研究如何彻底的隔离环境，不如研究如何解析需求。

对于python项目来说，唯一能真正处理插件引用的方式，反而就是要求插件提供requirements.txt，我们插件市场解析这个requirements.txt并判断本地环境是否满足该插件的条件。

2022-10-25 04:15 UTC, hsyhhssyy commented
我暂时注释掉了执行pip的代码，现在的pr仅包含user meta和lazyload

2022-10-25 04:31 UTC, vivien8261 commented
> 关于插件系统，我稍微多一嘴。 我觉得，以python的语言能力，以你现在的模式来提供插件功能，就必然意味着放弃了exe部署的能力，这两者是冲突的，以exe方式（pyinstaller ）发布的产品，天然就无法再加载任何插件，因为目前你的插件设计机制不是http进程隔离，而是直接代码引入。 （我其实前几天在群里讨论进程间通信的时候好像提过一嘴，说我认为目前进程间通信的最优解就是http，当然也可能是别的群） 而代码引入，就必然会导致环境污染和库污染，这是无法解决的问题。 与其研究如何彻底的隔离环境，不如研究如何解析需求。
> 
> 对于python项目来说，唯一能真正处理插件引用的方式，反而就是要求插件提供requirements.txt，我们插件市场解析这个requirements.txt并判断本地环境是否满足该插件的条件。

不冲突，现在 exe 部署反响还是比较好的，未来也会继续以 exe 部署为主方向。

2022-10-25 04:34 UTC, vivien8261 commented
> 你们上面讨论了pip的问题 这里我回答一下LazyLoad的问题 LazyLoad为什么放在这里而不是Core，是因为，不管是原来的PluginInstance，还是LazyLoadPluginInstance，他们加载的代码都在这里，也就是说使用者在这里。 如果你把他移动到core，那么“确保load函数在所有插件加载完成后才被执行”这个条件就无法保证了。 如果一个开发者单独使用core，那么这个LazyLoadPluginInstance对他毫无用处，因为插件的加载顺序是由他代码控制的。
> 
> 事实上，这也是我的一个疑惑的点，为什么，明明加载插件的能力，被你设计为是core的能力，但是加载插件的代码，却在本仓库的代码里。 对于纯core开发者来说，你提供的插件功能毫无意义，因为他既不能自动加载，也不提供插件管理，对于这样的开发者，你的插件加载功能，和importlib函数没有任何区别。

core 只是约束了插件的形式和把on_message加载进主体的逻辑，本仓库是运用的具体实现，需不需要自动加载插件属于业务需求。

2022-10-25 05:37 UTC, hsyhhssyy commented
> > 你们上面讨论了pip的问题 这里我回答一下LazyLoad的问题 LazyLoad为什么放在这里而不是Core，是因为，不管是原来的PluginInstance，还是LazyLoadPluginInstance，他们加载的代码都在这里，也就是说使用者在这里。 如果你把他移动到core，那么“确保load函数在所有插件加载完成后才被执行”这个条件就无法保证了。 如果一个开发者单独使用core，那么这个LazyLoadPluginInstance对他毫无用处，因为插件的加载顺序是由他代码控制的。
> > 事实上，这也是我的一个疑惑的点，为什么，明明加载插件的能力，被你设计为是core的能力，但是加载插件的代码，却在本仓库的代码里。 对于纯core开发者来说，你提供的插件功能毫无意义，因为他既不能自动加载，也不提供插件管理，对于这样的开发者，你的插件加载功能，和importlib函数没有任何区别。
> 
> core 只是约束了插件的形式和把on_message加载进主体的逻辑，本仓库是运用的具体实现，需不需要自动加载插件属于业务需求。

所以我这里认为，这个类想要实现的功能，也属于业务需求（控制加载顺序这个需求，只会出现在自动加载插件的情况下），应该属于业务代码，因此不应该加入core里。
如果真要调整core，那应该是直接修改PluginInstance并加入空load函数的改法更适合core。

2022-10-25 09:25 UTC, vivien8261 approved these changes

2022-10-25 09:26 UTC, merged